In [1]:
import os
import json
import argparse
import numpy as np
import pandas as pd
import pickle

import tensorflow as tf
from sklearn.model_selection import train_test_split

2023-07-18 13:20:20.733626: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
from SmartHomeHARLib.datasets.casas import Aruba
from SmartHomeHARLib.datasets.casas import Milan
from SmartHomeHARLib.datasets.casas import Cairo

In [19]:
dataset = Aruba()
#dataset = Cairo()
#dataset = Milan()

Load dataset

In [20]:
df = dataset.df

In [21]:
df

                          datetime sensor value  activity activityState
0       2010-11-04 00:03:50.209589   M003    ON  Sleeping         begin
1       2010-11-04 00:03:57.399391   M003   OFF  Sleeping           NaN
2       2010-11-04 00:15:08.984841   T002  21.5  Sleeping           NaN
3       2010-11-04 00:30:19.185547   T003    21  Sleeping           NaN
4       2010-11-04 00:30:19.385336   T004    21  Sleeping           NaN
...                            ...    ...   ...       ...           ...
1713123 2011-06-11 23:42:59.285070   T002  25.5  Sleeping           NaN
1713124 2011-06-11 23:48:02.888409   T001  23.5  Sleeping           NaN
1713125 2011-06-11 23:48:02.988798   T002    25  Sleeping           NaN
1713126 2011-06-11 23:53:06.429200   T002  25.5  Sleeping           NaN
1713127 2011-06-11 23:58:10.004834   T002    25  Sleeping           end

[1713128 rows x 5 columns]

In [22]:
df['hour'] = df['datetime'].dt.hour.astype(int) + 1
#df['hour'] = df['hour'].replace(to_replace = 0, value = 24)
df['minutes'] = df['datetime'].dt.minute.astype(int) + 1
df['secondes'] = df['datetime'].dt.second.astype(int) + 1
df['weekday'] = df['datetime'].dt.dayofweek.astype(int) + 1

In [23]:
df[:60]

,datetime,sensor,value,activity,activityState,hour,minutes,secondes,weekday
0,2010-11-04 00:03:50.209589,M003,ON,Sleeping,begin,1,4,51,4
1,2010-11-04 00:03:57.399391,M003,OFF,Sleeping,NaN,1,4,58,4
2,2010-11-04 00:15:08.984841,T002,21.5,Sleeping,NaN,1,16,9,4
3,2010-11-04 00:30:19.185547,T003,21,Sleeping,NaN,1,31,20,4
4,2010-11-04 00:30:19.385336,T004,21,Sleeping,NaN,1,31,20,4
5,2010-11-04 00:35:22.245870,T005,20.5,Sleeping,NaN,1,36,23,4
6,2010-11-04 00:40:25.428962,T005,21,Sleeping,NaN,1,41,26,4
7,2010-11-04 00:45:28.658171,T005,20.5,Sleeping,NaN,1,46,29,4
8,2010-11-04 01:05:42.269469,T001,20,Sleeping,NaN,2,6,43,4
9,2010-11-04 01:15:48.936777,T002,21,Sleeping,NaN,2,16,49,4
10,2010-11-04 01:30:59.100184,T003,20.5,Sleeping,NaN,2,31,60,4
11,2010-11-04 01:46:09.301846,T005,20,Sleeping,NaN,2,47,10,4
12,2010-11-04 01:56:16.059687,T004,20.5,Sleeping,NaN,2,57,17,4
13,2010-11-04 02:21:32.138203,T001,19.5,Sleeping,NaN,3,22,33,4
14,2010-11-04 02:21:32.228625,T002,20.5,Sleeping,NaN,3,22,33,4
15,2010-11-04 02:32:33.351906,M003,ON,Sleeping,NaN,3,33,34,4
16,2010-11-04 02:32:38.895958,M003,OFF,Sleeping,NaN,3,33,39,4
17,2010-11-04 02:41:45.231875,T003,20,Sleeping,NaN,3,42,46,4
18,2010-11-04 02:56:55.529628,T005,19.5,Sleeping,NaN,3,57,56,4
19,2010-11-04 03:22:11.942589,T004,20,Sleeping,NaN,4,23,12,4
20,2010-11-04 03:42:21.823650,M003,ON,Sleeping,NaN,4,43,22,4
21,2010-11-04 03:42:25.128495,T002,20,Sleeping,NaN,4,43,26,4
22,2010-11-04 03:42:25.939730,M003,OFF,Sleeping,NaN,4,43,26,4
23,2010-11-04 03:49:52.412755,M003,ON,Sleeping,NaN,4,50,53,4
24,2010-11-04 03:49:57.473649,M003,OFF,Sleeping,NaN,4,50,58,4
25,2010-11-04 03:57:34.772738,T001,19,Sleeping,NaN,4,58,35,4
26,2010-11-04 03:57:34.856793,T003,19.5,Sleeping,NaN,4,58,35,4
27,2010-11-04 04:14:32.835757,M003,ON,Sleeping,NaN,5,15,33,4
28,2010-11-04 04:14:33.203704,M002,ON,Sleeping,NaN,5,15,34,4
29,2010-11-04 04:14:37.155090,M002,OFF,Sleeping,NaN,5,15,38,4
30,2010-11-04 04:14:39.470621,M003,OFF,Sleeping,NaN,5,15,40,4
31,2010-11-04 04:32:57.624613,T005,19,Sleeping,NaN,5,33,58,4
32,2010-11-04 04:34:17.621670,M003,ON,Sleeping,NaN,5,35,18,4
33,2010-11-04 04:34:19.224926,M002,ON,Sleeping,NaN,5,35,20,4
34,2010-11-04 04:34:20.849595,M002,OFF,Sleeping,NaN,5,35,21,4
35,2010-11-04 04:34:21.407224,M003,OFF,Sleeping,NaN,5,35,22,4
36,2010-11-04 04:43:04.147940,T004,19.5,Sleeping,NaN,5,44,5,4
37,2010-11-04 05:13:23.803730,T002,19.5,Sleeping,NaN,6,14,24,4
38,2010-11-04 05:18:27.278517,T001,18.5,Sleeping,NaN,6,19,28,4
39,2010-11-04 05:33:37.200386,T003,19,Sleeping,NaN,6,34,38,4
40,2010-11-04 05:40:27.708148,M003,ON,Sleeping,NaN,6,41,28,4
41,2010-11-04 05:40:29.816524,M002,ON,Sleeping,NaN,6,41,30,4
42,2010-11-04 05:40:32.342225,M007,ON,Sleeping,NaN,6,41,33,4
43,2010-11-04 05:40:33.109478,M002,OFF,Sleeping,NaN,6,41,34,4
44,2010-11-04 05:40:34.522278,M007,OFF,Sleeping,NaN,6,41,35,4
45,2010-11-04 05:40:40.482626,M003,OFF,Sleeping,NaN,6,41,41,4
46,2010-11-04 05:40:40.844463,M003,ON,Sleeping,NaN,6,41,41,4
47,2010-11-04 05:40:42.452746,M007,ON,Sleeping,NaN,6,41,43,4
48,2010-11-04 05:40:43.642664,M003,OFF,Sleeping,end,6,41,44,4
49,2010-11-04 05:40:44.223548,M003,ON,Other,NaN,6,41,45,4
50,2010-11-04 05:40:45.939846,M005,ON,Other,NaN,6,41,46,4
51,2010-11-04 05:40:46.310862,M003,OFF,Other,NaN,6,41,47,4
52,2010-11-04 05:40:51.303739,M004,ON,Bed_to_Toilet,begin,6,41,52,4
53,2010-11-04 05:40:52.342105,M005,OFF,Bed_to_Toilet,NaN,6,41,53,4
54,2010-11-04 05:40:57.176409,M007,OFF,Bed_to_Toilet,NaN,6,41,58,4
55,2010-11-04 05:40:57.941486,M004,OFF,Bed_to_Toilet,NaN,6,41,58,4
56,2010-11-04 05:43:24.021475,M004,ON,Bed_to_Toilet,NaN,6,44,25,4
57,2010-11-04 05:43:26.273181,M004,OFF,Bed_to_Toilet,NaN,6,44,27,4
58,2010-11-04 05:43:26.345503,M007,ON,Bed_to_Toilet,NaN,6,44,27,4
59,2010-11-04 05:43:26.793102,M004,ON,Bed_to_Toilet,NaN,6,44,27,4

In [24]:
#df['week'] = df['datetime'].apply(lambda x: x.weekofyear if x.weekday() <= 6 else x.weekofyear+1)
df['week'] = df['datetime'].dt.isocalendar().week.astype(int)

In [25]:
df[29348:29398
]

,datetime,sensor,value,activity,activityState,hour,minutes,secondes,weekday,week
29348,2010-11-07 23:50:54.709651,M003,ON,Other,NaN,24,51,55,7,44
29349,2010-11-07 23:50:58.295552,M003,OFF,Other,NaN,24,51,59,7,44
29350,2010-11-07 23:51:04.643101,M003,ON,Other,NaN,24,52,5,7,44
29351,2010-11-07 23:51:07.555403,M008,ON,Other,NaN,24,52,8,7,44
29352,2010-11-07 23:51:07.625005,M003,OFF,Other,NaN,24,52,8,7,44
29353,2010-11-07 23:51:07.718853,M020,ON,Other,NaN,24,52,8,7,44
29354,2010-11-07 23:51:10.531130,M008,OFF,Other,NaN,24,52,11,7,44
29355,2010-11-07 23:51:10.923748,M020,OFF,Other,NaN,24,52,11,7,44
29356,2010-11-07 23:51:13.556385,M020,ON,Other,NaN,24,52,14,7,44
29357,2010-11-07 23:51:14.562280,M008,ON,Other,NaN,24,52,15,7,44
29358,2010-11-07 23:51:16.171042,M008,OFF,Other,NaN,24,52,17,7,44
29359,2010-11-07 23:51:20.384303,M020,OFF,Other,NaN,24,52,21,7,44
29360,2010-11-07 23:51:23.775413,M020,ON,Other,NaN,24,52,24,7,44
29361,2010-11-07 23:51:26.167141,M020,OFF,Other,NaN,24,52,27,7,44
29362,2010-11-07 23:51:27.354921,M014,ON,Other,NaN,24,52,28,7,44
29363,2010-11-07 23:51:27.437541,M020,ON,Other,NaN,24,52,28,7,44
29364,2010-11-07 23:51:29.635070,M014,OFF,Other,NaN,24,52,30,7,44
29365,2010-11-07 23:51:31.932920,M020,OFF,Other,NaN,24,52,32,7,44
29366,2010-11-07 23:51:32.705411,M020,ON,Other,NaN,24,52,33,7,44
29367,2010-11-07 23:51:35.387233,M020,OFF,Other,NaN,24,52,36,7,44
29368,2010-11-07 23:51:37.503193,M020,ON,Other,NaN,24,52,38,7,44
29369,2010-11-07 23:51:44.710860,M020,OFF,Other,NaN,24,52,45,7,44
29370,2010-11-07 23:51:45.487044,M020,ON,Other,NaN,24,52,46,7,44
29371,2010-11-07 23:51:48.071478,M020,OFF,Other,NaN,24,52,49,7,44
29372,2010-11-07 23:51:48.976727,M020,ON,Other,NaN,24,52,49,7,44
29373,2010-11-07 23:51:53.841731,M008,ON,Other,NaN,24,52,54,7,44
29374,2010-11-07 23:51:54.604465,M006,ON,Other,NaN,24,52,55,7,44
29375,2010-11-07 23:51:56.664966,M020,OFF,Other,NaN,24,52,57,7,44
29376,2010-11-07 23:51:57.076269,M008,OFF,Other,NaN,24,52,58,7,44
29377,2010-11-07 23:51:58.419211,M007,ON,Other,NaN,24,52,59,7,44
29378,2010-11-07 23:51:59.815112,M006,OFF,Other,NaN,24,52,60,7,44
29379,2010-11-07 23:52:00.212517,M007,OFF,Other,NaN,24,53,1,7,44
29380,2010-11-07 23:52:03.472616,M003,ON,Sleeping,begin,24,53,4,7,44
29381,2010-11-07 23:52:04.865368,M003,OFF,Sleeping,NaN,24,53,5,7,44
29382,2010-11-07 23:52:05.884728,M003,ON,Sleeping,NaN,24,53,6,7,44
29383,2010-11-07 23:52:11.435523,M003,OFF,Sleeping,NaN,24,53,12,7,44
29384,2010-11-07 23:52:12.400493,M003,ON,Sleeping,NaN,24,53,13,7,44
29385,2010-11-07 23:52:19.358571,M003,OFF,Sleeping,NaN,24,53,20,7,44
29386,2010-11-07 23:52:25.734202,M003,ON,Sleeping,NaN,24,53,26,7,44
29387,2010-11-07 23:52:36.545333,M003,OFF,Sleeping,NaN,24,53,37,7,44
29388,2010-11-08 00:03:31.006420,T001,20,Sleeping,NaN,1,4,32,1,45
29389,2010-11-08 00:03:31.103884,T004,21,Sleeping,NaN,1,4,32,1,45
29390,2010-11-08 00:08:34.313952,T002,21,Sleeping,NaN,1,9,35,1,45
29391,2010-11-08 00:11:43.501975,M003,ON,Sleeping,NaN,1,12,44,1,45
29392,2010-11-08 00:11:45.194574,M003,OFF,Sleeping,NaN,1,12,46,1,45
29393,2010-11-08 00:11:47.732541,M003,ON,Sleeping,NaN,1,12,48,1,45
29394,2010-11-08 00:11:57.856650,M002,ON,Sleeping,NaN,1,12,58,1,45
29395,2010-11-08 00:11:57.925918,M003,OFF,Sleeping,NaN,1,12,58,1,45
29396,2010-11-08 00:11:58.865085,M002,OFF,Sleeping,NaN,1,12,59,1,45
29397,2010-11-08 00:12:00.701191,M002,ON,Sleeping,NaN,1,13,1,1,45

In [26]:
def split_dataset_into_week(df):

    chunks = []

    transitionIndex = df.week.ne(df.week.shift())
    ii = np.where(transitionIndex == True)[0]
    

    for i, end in enumerate(ii):
        if i > 0:
            start = ii[i - 1]

            # activitySeq = self.df[start:end]
            if(len(df[start:end])>1):
                chunks.append(df[start:end])

    # lastActivitySeq = self.df[end:]

    if(len(df[end:])>1):
        chunks.append(df[end:])

    return chunks

In [27]:
weeks = split_dataset_into_week(df)

In [28]:
train_data, test_data = train_test_split(weeks, test_size=0.3, random_state=42)

In [29]:
# Convert the training and testing sets back into a list of DataFrames
train_data = [pd.DataFrame(train_data[i]) for i in range(len(train_data))]
test_data = [pd.DataFrame(test_data[i]) for i in range(len(test_data))]

In [30]:
train_data[0]

,datetime,sensor,value,activity,activityState,hour,minutes,secondes,weekday,week
173681,2010-11-29 00:00:05.424831,M009,OFF,Relax,NaN,1,1,6,1,48
173682,2010-11-29 00:03:34.011945,M009,ON,Relax,NaN,1,4,35,1,48
173683,2010-11-29 00:03:35.830651,M009,OFF,Relax,NaN,1,4,36,1,48
173684,2010-11-29 00:04:42.650997,T004,21,Relax,NaN,1,5,43,1,48
173685,2010-11-29 00:14:11.411195,M009,ON,Relax,NaN,1,15,12,1,48
...,...,...,...,...,...,...,...,...,...,...
225428,2010-12-05 23:57:18.165090,M002,ON,Sleeping,NaN,24,58,19,7,48
225429,2010-12-05 23:57:22.343125,M002,OFF,Sleeping,NaN,24,58,23,7,48
225430,2010-12-05 23:57:23.331223,M003,OFF,Sleeping,NaN,24,58,24,7,48
225431,2010-12-05 23:57:56.445867,M002,ON,Sleeping,NaN,24,58,57,7,48
225432,2010-12-05 23:58:00.906550,M002,OFF,Sleeping,NaN,24,59,1,7,48

In [31]:
dataset.name.lower()

'aruba'

In [32]:
# Save the list of DataFrames to a pickle file
with open("datasets/"+dataset.name.lower()+'_train_data_time.pickle', 'wb') as f:
    pickle.dump(train_data, f)

In [33]:
# Save the list of DataFrames to a pickle file
with open("datasets/"+dataset.name.lower()+'_test_data_time.pickle', 'wb') as f:
    pickle.dump(test_data, f)

In [34]:
# Load the list of DataFrames from the pickle file
with open("datasets/"+dataset.name.lower()+'_train_data_time.pickle', 'rb') as f:
    df_list = pickle.load(f)